<<<<<<< HEAD
app = "langflowbubblemvp"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "7860"
  HOST = "0.0.0.0"
  LANGFLOW_FLOWS_DIR = "/app/flows"
  LANGFLOW_MEMORY_LIMIT = "3GB"
=======
# fly.toml app configuration file generated for langflowbubblemvp on 2025-05-19T14:00:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'langflowbubblemvp'
primary_region = 'lhr'

[build]
>>>>>>> 72e2d3c9f0d26697e1f4309aa74be6e9f912aae7

[http_service]
  internal_port = 7860
  force_https = true
<<<<<<< HEAD
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "30s"
    method = "GET"
    path = "/"
    protocol = "http"
    tls_skip_verify = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 3072 
=======
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
>>>>>>> 72e2d3c9f0d26697e1f4309aa74be6e9f912aae7
