# fly.toml app configuration file generated for langflowbubblemvp on 2025-05-19T15:13:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'langflowbubblemvp'
primary_region = 'lhr'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '3gb'
  memory_mb = 3_072

[[mounts]]
  source = "langflow_data_1"
  destination = "/app/data"

[[mounts]]
  source = "langflow_data_2"
  destination = "/app/data_backup"
